port: 7880
rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 60000
  use_external_ip: true

redis:
  address: localhost:6379

keys:
  # Replace with generated keys
  your-api-key: your-api-secret

logging:
  level: info

turn:
  enabled: true
  domain: turn.yourdomain.com
  tls_port: 443
  udp_port: 3478

room:
  empty_timeout: 300
  max_participants: 10

webhook:
  urls: []
